name: CI API

on:
  push:
    branches: [main]
    paths:
     - 'api/**'
  pull_request:
    branches: [main]
    paths:
     - 'api/**'
    
jobs:
  test_and_report_coverage:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: api
    steps:
      - uses: actions/checkout@v3
      - name: Setup dotnet
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: 6.0.x
      - name: Install dependencies
        run: dotnet restore
      - name: Test with dotnet
        run: dotnet test --collect:"XPlat Code Coverage" --settings coverlet.runsettings --results-directory "./coverage"
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3
        if: always()
        with:
          flags: api
