name: CI Angular

# Controls when the workflow will run
on:
  push:
    branches: [main, dev, staging]
    paths:
     - 'ng-landing/**'
  pull_request:
    types: [opened, synchronize, reopened]
    paths:
     - 'ng-landing/**'

jobs:
  lint-and-test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ng-landing
    name: angular test coverage update
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Run lint and tests
        run: |
          npm i
          npm run test-ci
      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@master
        if: always()
        with:
          projectBaseDir: ng-landing
          args: >
            -Dsonar.organization=chill-viking-org
            -Dsonar.projectKey=chill-viking-org_static-web-app-landing-ng-app
            -Dsonar.sources=src
            -Dsonar.tests=src
            -Dsonar.test.inclusions=src/**/*.spec.ts
            -Dsonar.coverage.exclusions=src/**/*.spec.ts
            -Dsonar.javascript.lcov.reportPaths=coverage/lcov.info
            -Dsonar.typescript.tsconfigPath=tsconfig.app.json
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Needed to get PR information, if any
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN_NG }}
