name: CI API

on:
  pull_request:
    branches: [ "main" ]
    paths:
     - 'api/**'
    
jobs:
  test_and_report_coverage:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: api
    steps:
      - uses: actions/checkout@v3
      - name: Setup dotnet
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: 6.0.x
      - name: Install dependencies
        run: dotnet restore
      - name: Test with dotnet
        run: dotnet test --collect:"XPlat Code Coverage" --settings coverlet.runsettings --results-directory "./coverage"
      - name: Generate coverage report
        if: ${{ always() }}
        uses: romeovs/lcov-reporter-action@v0.2.16
        with:
          lcov-file: ./coverage/**/coverage.info
